services:
  whoami:
    image: containous/whoami
    labels:
      # Enable Traefik auto discovery.
      - "traefik.enable=true"
      # Set the domain. You can customize the name of the router — `routers.whoami` — below.
      - "traefik.http.routers.whoami.rule=Host(`whoami.local.crz.li`)"
      # Enable TLS.
      - "traefik.http.routers.whoami.tls=true"
      # Traefik selects the first port that the service publishes, but if you need you can point to a different port with the line below.
      # - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      # The `default` network is automatically created by Docker Compose, but the container also needs to be connected to the Traefik network.
      - default
      - traefik

# Declare the Traefik network to be external.
networks:
  traefik:
    external: true
